CREATE TABLE IF NOT EXISTS USER (
  ID BIGINT IDENTITY PRIMARY KEY
, FIRST_NAME VARCHAR2(50) NOT NULL
, LAST_NAME VARCHAR2(50) NOT NULL
, EMAIL VARCHAR2(50) NOT NULL
, PASSWORD TEXT NOT NULL
, CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
, MODIFIED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS VEHICLE (
  ID BIGINT IDENTITY PRIMARY KEY
, NAME VARCHAR2(50) NOT NULL
, USER_ID VARCHAR2(50) NOT NULL
, CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
, MODIFIED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

ALTER TABLE VEHICLE ADD FOREIGN KEY(USER_ID) REFERENCES USER(ID);