CREATE TABLE IF NOT EXISTS USER (
  ID BIGINT IDENTITY PRIMARY KEY
, USER_CODE VARCHAR2(50) NOT NULL
, FIRST_NAME VARCHAR2(50) NOT NULL
, LAST_NAME VARCHAR2(50) NOT NULL
, EMAIL VARCHAR2(50) NOT NULL
, PASSWORD TEXT NOT NULL
, ROLE VARCHAR2(50) NOT NULL
, CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
, MODIFIED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS USER_CODE_IDX ON USER(USER_CODE);

CREATE TABLE IF NOT EXISTS VEHICLE (
  ID BIGINT IDENTITY PRIMARY KEY
, VEHICLE_CODE VARCHAR2(50) NOT NULL
, NAME VARCHAR2(50) NOT NULL
, USER_ID VARCHAR2(50)
, CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
, MODIFIED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

ALTER TABLE VEHICLE ADD FOREIGN KEY(USER_ID) REFERENCES USER(ID);
CREATE INDEX IF NOT EXISTS VEHICLE_CODE_IDX ON VEHICLE(VEHICLE_CODE);